### PR TITLE
Fixed issues

### PR DESCRIPTION
**Pull request by DizzasTeR**
Attempted to fix following:
- #17 
- #10 
- #12
- #13 

About issue 12 and 13: I could not reproduce the issue before so not sure if they actually got fixed

A few other fixes including UI fixes and text color not updating with slider

I also forced a few theme colors (mainly dark) to stop the entire mess of colors mixing up

Most dependencies were updated

### CODE REVIEW

**Comment by Stefi16** [comment]
Hey, I recieve the following errors after running the code:
../Downloads/flutter/.pub-cache/git/image_editor_plus-25a3815edb84770bf6a854ec20459485f401dae9/lib/image_editor_plus.dart:1290:38: Error: The method 'build' isn't defined for the class 'ColorFilterGenerator'.
 - 'ColorFilterGenerator' is from 'package:colorfilter_generator/colorfilter_generator.dart' ('../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/colorfilter_generator-0.0.6/lib/colorfilter_generator.dart').
Try correcting the name to the name of an existing method, or defining a method named 'build'.
                    : selectedFilter.build(
                                     ^^^^^
../Downloads/flutter/.pub-cache/git/image_editor_plus-25a3815edb84770bf6a854ec20459485f401dae9/lib/image_editor_plus.dart:1405:21: Error: The method 'build' isn't defined for the class 'ColorFilterGenerator'.
 - 'ColorFilterGenerator' is from 'package:colorfilter_generator/colorfilter_generator.dart' ('../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/colorfilter_generator-0.0.6/lib/colorfilter_generator.dart').
Try correcting the name to the name of an existing method, or defining a method named 'build'.
      child: filter.build(
                    ^^^^^
../Downloads/flutter/.pub-cache/git/image_editor_plus-25a3815edb84770bf6a854ec20459485f401dae9/lib/image_editor_plus.dart:1535:18: Error: The method 'HandSignaturePainterView' isn't defined for the class '_ImageEditorDrawingState'.
 - '_ImageEditorDrawingState' is from 'package:image_editor_plus/image_editor_plus.dart' ('../Downloads/flutter/.pub-cache/git/image_editor_plus-25a3815edb84770bf6a854ec20459485f401dae9/lib/image_editor_plus.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HandSignaturePainterView'.
          child: HandSignaturePainterView(

**Comment by DizzasTeR** [comment]
Not sure why you're getting that, I changed the dependency package to my fork and it works fine. If it only happens when using my fork then I'll take a look

**Comment by Stefi16** [comment]
Yes it happens only using your forked repository

**Comment by DizzasTeR** [comment]
> Yes it happens only using your forked repository

Hmm, okay I'll see whats wrong then, maybe it works for me because of some cache thing, i'll try on a fresh project and let you know

**Comment by DizzasTeR** [comment]
@Stefi16  Whats your compiledSdkVersion in <project>/android/app/build.gradle

**Comment by Stefi16** [comment]
@DizzasTeR 31

**Comment by DizzasTeR** [comment]
@Stefi16 Pushed some changes, pub get and pub upgrade and give it a go. Also you might need compiledSdkVersion of 33 and minSdkVersion 21 for some dependencies to work (Concluded this by starting a fresh project, and adding this package as dependency only)

**Comment by Stefi16** [comment]
Okay will test it thank you.

**Comment by volodymyr-perveev** [comment]
merge plese)

**Comment by hsbijarniya** [comment]
@DizzasTeR please update conflicting files.

**Review by hsbijarniya — APPROVED** [review]

**Pull request merged**
