### PR TITLE
Add simple example

### PR DESCRIPTION
**Pull request by mjablecnik**

### CODE REVIEW

**Review by hsbijarniya — CHANGES_REQUESTED** [review]
pub.dev will require single "example/main.dart" not a flutter project inside example directory.

**Comment by mjablecnik** [comment]
> pub.dev will require single "example/main.dart" not a flutter project inside example directory.

It is not true. In example can be also Flutter project.

You can see it for example here:
https://pub.dev/packages/my_logger/example
https://github.com/mjablecnik/MyLogger/tree/master/example

where is also flutter project as example.

**Comment by hsbijarniya** [comment]
See the pub.dev guidelines

**Comment by mjablecnik** [comment]
There is nothing about what you say :)

https://dart.dev/tools/pub/package-layout
image

**Comment by hsbijarniya** [comment]
Ok thanks

**Pull request merged**
